prueba:
  test: ${password}
spring:
  application.name: person
  cloud:
    aws:
      region:
        static: us-east-1
      secretsmanager:
        enabled: true
        name: prod/secrets/database-secrets
  datasource:
    schema: foods_scheme
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: jdbc-secretsmanager:mysql://${RDS_HOST}:3306/people?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: prod/secrets/database-secrets
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect